# A brief intro to NumPy

In [1]:
import numpy as np

## Creating arays

In [2]:
np.zeros(5) #argument is the size

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 4, 5, 12])
a

array([ 1,  2,  3,  4,  5, 12])

In [7]:
# accesibg to an element 
a[2] # position number 3

3

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5, 12])

In [11]:
np.arange(10) #from 0 to 9, an 10 size array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3, 10) #similar to range

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 10) # array with number from a to b at certain size

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## multi-dimentional arrays

In [16]:
# elements inside the tuple ROWS, COLS
np.zeros((5, 2))  

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
# from a python list
n =  np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# accesing to elements just is ROW and COl
n[0, 1]

2

In [19]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
## accesing to entire row
n[0]

array([ 1, 20,  3])

In [21]:
# assing new values to a row 
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
## accesing to a column (second column example)
n[:, 1]

array([20,  5,  1])

In [23]:
# assing somethin to a column
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [24]:
np.random.rand(5, 2) # 5 row, 2 cols

array([[0.94203997, 0.47328611],
       [0.71161433, 0.77050518],
       [0.94882344, 0.46775665],
       [0.21125042, 0.20319696],
       [0.87805703, 0.9953603 ]])

In [28]:
# to get the same number, plant a seed (reproducibility)
# randn is for normal distribution
np.random.seed(10)
np.random.rand(5, 2) # 5 row, 2 cols

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [29]:
100 * np.random.rand(5, 2)

array([[68.53598184, 95.33933462],
       [ 0.39482663, 51.21922634],
       [81.26209617, 61.25260668],
       [72.17553174, 29.18760682],
       [91.77741225, 71.45757834]])

In [33]:
# random integers 
np.random.seed(10)
np.random.randint(low=0, high=100, size=(5,2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

## element wise operations

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
# add a number for every element
a + 1 

array([1, 2, 3, 4, 5])

In [36]:
# similar to add works multiply and divide
a * 100

array([  0, 100, 200, 300, 400])

In [37]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [38]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [40]:
a

array([0, 1, 2, 3, 4])

In [39]:
# diferent arrays get the sum of every element 
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [41]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## comparison operations

In [42]:
a

array([0, 1, 2, 3, 4])

In [43]:
a >= 2

array([False, False,  True,  True,  True])

In [44]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [46]:
# elemnts of array a are compared with array b
a > b

array([False, False,  True,  True,  True])

In [47]:
# return all the true in the a array
a[a > b]

array([2, 3, 4])

## summarizing operations

In [48]:
a

array([0, 1, 2, 3, 4])

In [49]:
a.min()

0

In [50]:
a.sum()

10

In [51]:
a.mean()

2.0

In [52]:
a.std()

1.4142135623730951

In [54]:
# also works on two dimensional arrays 
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [55]:
n.min()

0

In [56]:
n.sum() # and more...

35